# Welcome to Jekyll!

locale                   : "en-US"
site_theme               : "default"
title                    : "Eng. Tefera Addis"
title_separator          : "-"
name                     : &name "Tefera Addis"
description              : &description "Your Name's academic portfolio"
url                      : https://tefera-addis-sisay.github.io
baseurl                  : ""
repository               : "tefera-addis-sisay/tefera-addis-sisay.github.io"

author:
  avatar           : "profile.png"
  name             : "Tefera Addis SISAY"
  bio              : "Lecturer at Bahir Dar Institute of Technology (BiT), Bahir Dar, Ethiopia."
  location         : "Ethiopia"
  employer         : "Bahir Dar Institute of Technology"
  email            : "tefera.addis@bdu.edu.et"

  googlescholar    : "https://scholar.google.com/citations?view_op=new_articles&hl=en&imq=Tefera+Addis#"
  orcid            : "https://orcid.org/my-orcid?orcid=0009-0005-7483-7377"
  researchgate     : "https://www.researchgate.net/profile/Tefera-Addis-Sisay-3?ev=hdr_xprf"
  linkedin         : "https://www.linkedin.com/in/tefera-addis-a3b475343/"
  twitter          : "https://x.com/teferaaddis777?s=21"
  youtube          : "Habeshatube777"

publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'
  conferences:
    title: 'Conference Papers'

include:
  - .htaccess
  - _pages
  - files

exclude:
  - node_modules
  - vendor

encoding: "utf-8"
markdown: kramdown
highlighter: rouge

collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  projects:   # ✅ FIXED (was project)
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
  services:
    output: true
    permalink: /:collection/:path/

defaults:

  # POSTS
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true

  # PAGES
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

  # TEACHING
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      show_date: false
      read_time: false
      comments: false

  # PUBLICATIONS
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true

  # PROJECTS (FIXED)
  - scope:
      path: ""
      type: projects   # ✅ FIXED
    values:
      layout: single
      author_profile: true
      share: true
      comments: false

  # SERVICES
  - scope:
      path: ""
      type: services
    values:
      layout: single
      author_profile: true
      share: true
      comments: false

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
timezone: Etc/UTC

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
